name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
          
      - name: Install poetry
        run: python3 -m pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests
        run: |
          poetry run coverage run -m pytest -v tests

      - name: Run coverage
        run: |
          poetry run coverage report -m --skip-empty --fail-under=100
        
      - name: Build documentation
        run: |
          poetry run mkdocs gh-deploy --force