name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
          
      - name: Install poetry
        run: python3 -m pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests
        run: |
          poetry run coverage run -m pytest -v tests

      - name: Run coverage
        run: |
          poetry run coverage report -m --skip-empty --fail-under=100

      - name: Coverage Badge
        run: |
          poetry run coverage-badge -f -o coverage.svg

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg"

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}

      - name: Create CNAME file
        run: |
          echo 'backend-dev-utils.melikbugraozcelik.com' > site/CNAME
        
      - name: Build documentation
        run: |
          poetry run mkdocs gh-deploy --force

      
